# Basic descriptions
title: Yara
author: 
  name: Yara
  email: 
  picture:  /assets/img/IMG_0224.jpeg
description: "Master student Computer Science"

# Theme settings
remote_theme: hydecorp/hydejack@v9.1.6

# Plugin list
plugins:
  - jekyll-include-cache
  - jekyll-avatar

# Blog in subdirectory
# paginate:      10
# paginate_path: /my-blog/:num/ #!!

# Sidebar
menu:
  - title: Certificates
    url:   /certificates/2024-05-22-CertifiedSecure.md
  - title: Resume
    url:   /resume/
  - title: Study Log
    url:   /study-log/
  - title: About
    url:   /_posts/2024-05-22-AboutMe.md
