# Basic descriptions
title: Yara
author: 
  name: Yara van Schendel
  picture:  /assets/img/IMG_0224.jpeg
  social:
    linkedin: yara-vanschendel-
    github:  yayayara
description: "Master student Computer Science at University of Twente"
tagline: "Master student Computer Science
lang: en
keywords: ["Cybersecurity", "Incident response", "digital forensics"]

# Theme settings
remote_theme: hydecorp/hydejack@v9.1.6

# Plugin list
plugins:
  - jekyll-include-cache
  - jekyll-avatar
  - jekyll-default-layout
  - jekyll-feed
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-titles-from-headings
  - jekyll-last-modified-at
  - jemoji

# Blog in subdirectory
# paginate:      10
# paginate_path: /my-blog/:num/ #!!

# Sidebar
menu:
  - title: Certificates
    url:   /certificates/_posts/
  - title: Resume
    url:   /resume/
  - title: Study Log
    url:   /study-log/_posts/
  - title: About
    url:   /_posts/

# This text will appear in a `<small>` tag in the footer of every page.
copyright:             © 2022. All rights reserved.

# Format of the permalinks
# permalink:             /blog/:categories/:year-:month-:day-:title/
permalink:             none

# Pagination configuration (used by the `blog` layout)
paginate:              10
paginate_path:         /page-:num/
excerpt_separator:     <!--more-->

# The string encoding which fonts to fetch from Google Fonts.
# See: <https://hydejack.com/docs/config/#changing-fonts>
google_fonts:          Noto+Sans+KR|JetBrains+Mono|Nanum+Gothic+Coding

# The text font. Expects a string that is a valid CSS font-family value.
# To change font-weight, see _sass/variables.scss
font:                  Noto Sans KR, Helvetica, Arial, sans-serif

# The font used for headings. Expects a string that is a valid CSS font-family value.
# To change font-weight, see _sass/variables.scss
font_heading:          Noto Sans KR, Helvetica, Arial, sans-serif

# The font used for code blocks. Expects a string that is a valid CSS font-family value.
font_code:             JetBrains Mono, Nanum Gothic Coding, Menlo, Monaco, Consolas, monospace;

# Don't include documents in assets in the sitemap
  - scope:
      path:            assets/**
    values:
      sitemap:         false

kramdown:
  math_engine:         mathjax
  math_engine_opts:    {}
  footnote_backlink:   '&#x21a9;&#xfe0e;'

hydejack:
  advertise:           false
  hide_dates:          false
  hide_last_modified:  false
  dark_mode:
    # Set to `true` to always use the dark theme.
    always:            true
    # Set to `true` to use the dark theme based on visitors' preference (OS setting).
    dynamic:           true
    # Set to `true` to allow visitors to switch between light and dark mode.
    icon:              false

collections:
  featured_categories:
    permalink:         /:name/
    output:            true
  featured_tags:
    permalink:         /tag-:name/
    output:            true
  projects:
    permalink:         /projects/:path/
    output:            true

exclude:
  - .jekyll-cache
  - .sass-cache
  - '*.toml'
  - vendor
  - Gemfile
  - Gemfile.lock
  - node_modules
include:
  - .well-known
  - LICENSE.md

optional_front_matter:
  remove_originals:    true

readme_index:
  remove_originals:    true
  with_frontmatter:    true

relative_links:
  collections:         true

titles_from_headings:
  strip_title:         true
  collections:         true

compress_html:
  comments:            ["<!-- ", " -->"]
  clippings:           all
  endings:             all
  ignore:
    envs:              [development]

sass:
  style:               compressed

# jekyll-feed settings
feed:
  categories:
    - studylog
    - about
    - certificates

