# Basic descriptions
title: Yara
author: 
  name: Yara van Schendel
  picture:  /assets/img/IMG_0224.jpeg
  social:
    linkedin: yara-vanschendel-
    github:  yayayara
description: "Master student Computer Science at University of Twente"
tagline: "Master student Computer Science
lang: en
keywords: ["Cybersecurity", "Incident response", "digital forensics"]

# Theme settings
remote_theme: hydecorp/hydejack@v9.1.6

# Plugin list
plugins:
  - jekyll-include-cache
  - jekyll-avatar

# Sidebar
menu:
  - title: Certificates
    url:   /certificates/_posts/
  - title: Resume
    url:   /resume/
  - title: Study Log
    url:   /study-log/_posts/
  - title: About
    url:   /_posts/

# Format of the permalinks
# permalink:             /blog/:categories/:year-:month-:day-:title/
permalink:             none

# Pagination configuration (used by the `blog` layout)
paginate:              10
paginate_path:         /page-:num/
excerpt_separator:     <!--more-->

# Don't include documents in assets in the sitemap
  - scope:
      path:            assets/**
    values:
      sitemap:         false

kramdown:
  math_engine:         mathjax
  math_engine_opts:    {}
  footnote_backlink:   '&#x21a9;&#xfe0e;'

hydejack:
  advertise:           false
  hide_dates:          false
  hide_last_modified:  false
  dark_mode:
    # Set to `true` to always use the dark theme.
    always:            true
    # Set to `true` to use the dark theme based on visitors' preference (OS setting).
    dynamic:           true
    # Set to `true` to allow visitors to switch between light and dark mode.
    icon:              false

# jekyll-feed settings
feed:
  categories:
    - studylog
    - about
    - certificates

