# Basic descriptions
title: Yara DFIR
author: Yara van Schendel
  # picture:  /assets/img/IMG_0224.jpeg
  social:
    linkedin: yara-vanschendel
    github:  yayayara
description: "Master student Computer Science at University of Twente"
# tagline: "Master student Computer Science"
# lang: en
# keywords: ["Cybersecurity", "Incident response", "digital forensics"]

# Theme settings
remote_theme: hydecorp/hydejack@v9.1.6

# Plugin list
plugins:
  - jekyll-include-cache
  - jekyll-avatar

# # Sidebar
# menu:
#   - title: Certificates
#     url:   /_posts/certificates
#   - title: CTF
#     url:   /_posts/ctf
#   - title: Resume
#     url:   /_posts/resume
#   - title: Study Log
#     url:   /_posts/studylog
#   - title: About
#     url:   about.md

# Pagination configuration (used by the `blog` layout)
# paginate:              10
# paginate_path:         /page-:num/
# excerpt_separator:     <!--more-->

# Add links to the sidebar.
menu:
  - title:             Resume
    url:               /_posts/resume/
  - title:             Certificates
    url:               /_posts/certificates/
  - title:             CTF
    url:               /_posts/ctf/
   - title:            Study Log
    url:               /_posts/studylog/
  - title:             About
    url:               /_posts/about/
