# General settings
# ---------------------------------------------------------------------------------------

# Language of your content in 2-letter code, e.g.: en, de.
# You may also provide a location, e.g.: en-us, de_AT.
lang:                  en

# The title of your blog. Used in the sidebar and the browser tab.
title:                 Yara-DFIR

# A short description (~150 chars) of the page used for the meta description tag.
# Can use markdown, but no more than one paragraph (enforced by `>`)
description:           >
  Master student Computer Science at University of Twente

# A shorter description for the sidebar.
tagline:               Master student Computer Science

# A list of keywords for your blog
keywords:              ["Cybersecurity", "Incident response", "digital forensics"]

# A (square) logo for your site.
# If provided, it will be shown at the top of the sidebar.
# It also used by the `jekyll-seo-tag` plugin.
logo:                  /assets/img/logo.png

# Basic descriptions
title: Yara
author: 
  name: Yara van Schendel
  picture:  /assets/img/IMG_0224.jpeg
  social:
    linkedin: yara-vanschendel-
    github:  yayayara
description: "Master student Computer Science at University of Twente"
tagline: "Master student Computer Science"
lang: en
keywords: ["Cybersecurity", "Incident response", "digital forensics"]

# Theme settings
remote_theme: hydecorp/hydejack@v9.1.6

# Plugin list
plugins:
  - jekyll-include-cache
  - jekyll-avatar

# # Sidebar
# menu:
#   - title: Certificates
#     url:   /_posts/certificates
#   - title: CTF
#     url:   /_posts/ctf
#   - title: Resume
#     url:   /_posts/resume
#   - title: Study Log
#     url:   /_posts/studylog
#   - title: About
#     url:   about.md

# Pagination configuration (used by the `blog` layout)
paginate:              10
paginate_path:         /page-:num/
excerpt_separator:     <!--more-->

# Add links to the sidebar.
menu:
  - title:             Resume
    url:               /resume/
  - title:             Certificates
    url:               /certificates/
  - title:             CTF
    url:               /ctf/
   - title:            Study Log
    url:               /studylog/
  - title:             About
    url:               /about/
