# Basic descriptions
title: Yara-DFIR
author: Yara
description: "My site where I publish my accomplishments and CTF writeups"

# Theme settings
remote_theme: hydecorp/hydejack@v9.1.6

# Accent colors and sidebar images
theme_color: rgb(98,131,148)

# Plugin list
plugins:
  - jekyll-include-cache
