# Basic descriptions
title: Yara
author: Yara
email: 
description: "Master student Computer Science"

# Theme settings
remote_theme: hydecorp/hydejack@v9.1.6

# Plugin list
plugins:
  - jekyll-include-cache

# Blog in subdirectory
# paginate:      10
# paginate_path: /my-blog/:num/ #!!

# Sidebar
menu:
  - title: Blog
    url:   /blog/
  - title: Certificates
    url:   /certificates/
  - title: Resume
    url:   /resume/
  - title: About
    url:   /about/
